tools:
    external_code_coverage:
        timeout: 600
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]
    sensiolabs_security_checker: true
