language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script:
  - ./vendor/bin/phpunit --coverage-clover=./build/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/
